# Generated by Django 5.1.6 on 2025-02-22 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('LIKE_NEW', 'Like New'), ('POOR', 'Poor')], default='USED', max_length=10)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
