# Generated by Django 5.1.6 on 2025-03-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_remove_books_category_remove_books_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='books',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
